# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('FUTURE', 'Future'), ('AT_HAND', 'At Hand'), ('FINISHED', 'Finished')], default='FUTURE', max_length=20, verbose_name='Status')),
                ('progress_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progress Percentage')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_project',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['progress_percentage'], name='projects_pr_progres_98568f_idx')],
            },
        ),
    ]
