# Generated by Django 5.2.12 on 2026-07-24 23:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_fundraising',
            field=models.BooleanField(default=False, help_text='Allow donations to be raised for this project.', verbose_name='Enable Fundraising'),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_amount_raised',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatically updated from confirmed donations.', max_digits=15, verbose_name='Amount Raised'),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fundraising End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Automatically calculated fundraising progress.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Progress Percentage'),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Automatically calculated from target minus raised.', max_digits=15, verbose_name='Remaining Amount'),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fundraising Start Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='fundraising_status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=20, verbose_name='Fundraising Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Target Amount'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['enable_fundraising'], name='projects_pr_enable__1c4a81_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['fundraising_status'], name='projects_pr_fundrai_c1965b_idx'),
        ),
    ]
