# Generated by Django 5.2.11 on 2026-02-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_budget_project_completed_by_tenure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('suspended', 'Suspended'), ('abandoned', 'Abandoned'), ('handed_over', 'Handed Over')], default='ongoing', max_length=20),
        ),
    ]
