# Generated by Django 5.2.12 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_include_in_group_reports'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_include_11f05d_idx',
            old_name='projects_incl_grprpt_idx',
        ),
    ]
