# Generated by Django 5.2.12 on 2026-07-24 23:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_member_year_joined_and_more'),
        ('projects', '0002_project_enable_fundraising_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideDonor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='donors/photos/%Y/%m/', verbose_name='Profile Picture')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10, verbose_name='Gender')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
                ('invited_by', models.ForeignKey(help_text='The OYA member who introduced this donor.', on_delete=django.db.models.deletion.PROTECT, related_name='invited_outside_donors', to='members.member', verbose_name='Invited By')),
            ],
            options={
                'verbose_name': 'Outside Donor',
                'verbose_name_plural': 'Outside Donors',
                'db_table': 'project_donations_outside_donor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor_type', models.CharField(choices=[('MEMBER', 'OYA Member'), ('OUTSIDE', 'Outside Donor')], max_length=10, verbose_name='Donor Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, max_length=255, verbose_name='Reference Number')),
                ('narration', models.TextField(blank=True, verbose_name='Narration')),
                ('donation_date', models.DateField(default=django.utils.timezone.now, verbose_name='Donation Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20, verbose_name='Status')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_donations', to='members.member', verbose_name='Invited By')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_donations', to='members.member', verbose_name='Member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='projects.project', verbose_name='Project')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
                ('outside_donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='project_donations.outsidedonor', verbose_name='Outside Donor')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'project_donations_donation',
                'ordering': ['-donation_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='outsidedonor',
            index=models.Index(fields=['full_name'], name='project_don_full_na_976798_idx'),
        ),
        migrations.AddIndex(
            model_name='outsidedonor',
            index=models.Index(fields=['invited_by'], name='project_don_invited_78d930_idx'),
        ),
        migrations.AddIndex(
            model_name='outsidedonor',
            index=models.Index(fields=['date_added'], name='project_don_date_ad_cdbfc4_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['project'], name='project_don_project_b53b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['member'], name='project_don_member__d2393a_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['outside_donor'], name='project_don_outside_8e62e0_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donation_date'], name='project_don_donatio_b59277_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='project_don_status_c58e77_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_type'], name='project_don_donor_t_ff33c6_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['invited_by'], name='project_don_invited_92cd4d_idx'),
        ),
    ]
