# Generated by Django 5.2.12 on 2026-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_year_joined_and_more'),
        ('project_donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='outsidedonor',
            name='project_don_date_ad_cdbfc4_idx',
        ),
        migrations.RemoveField(
            model_name='outsidedonor',
            name='date_added',
        ),
        migrations.AddIndex(
            model_name='outsidedonor',
            index=models.Index(fields=['created_at'], name='project_don_created_e2aff9_idx'),
        ),
    ]
