# Generated by Django 5.2.12 on 2026-07-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_duespayment_duespaymenttransaction_and_more'),
        ('project_donations', '0002_remove_outsidedonor_project_don_date_ad_cdbfc4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_donation', to='finance.income', verbose_name='Linked Income Record'),
        ),
    ]
