# Generated by Django 5.2.12 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_donations', '0004_donation_types_pledges'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='donation',
            new_name='project_don_donatio_d438a6_idx',
            old_name='proj_don_donationtype_idx',
        ),
        migrations.RenameIndex(
            model_name='pledge',
            new_name='project_don_member__d28cd4_idx',
            old_name='proj_don_pledge_member_idx',
        ),
        migrations.RenameIndex(
            model_name='pledge',
            new_name='project_don_project_aab1d1_idx',
            old_name='proj_don_pledge_project_idx',
        ),
        migrations.RenameIndex(
            model_name='pledge',
            new_name='project_don_status_e459b2_idx',
            old_name='proj_don_pledge_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pledge',
            new_name='project_don_due_dat_4def20_idx',
            old_name='proj_don_pledge_duedate_idx',
        ),
        migrations.RenameIndex(
            model_name='pledgepayment',
            new_name='project_don_pledge__dfab8a_idx',
            old_name='proj_don_pp_pledge_idx',
        ),
        migrations.RenameIndex(
            model_name='pledgepayment',
            new_name='project_don_payment_30327b_idx',
            old_name='proj_don_pp_paydate_idx',
        ),
    ]
