# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('category', models.CharField(choices=[('ADMINISTRATIVE', 'Administrative'), ('PROJECT', 'Project'), ('EVENT', 'Event'), ('MAINTENANCE', 'Maintenance'), ('SALARY', 'Salary'), ('OTHER', 'Other')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('receipt_file', models.FileField(upload_to='finance/receipts/%Y/%m/', verbose_name='Receipt File')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'finance_expense',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='finance_exp_categor_54fa26_idx'), models.Index(fields=['created_at'], name='finance_exp_created_86c65c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('paid_by', models.CharField(blank=True, max_length=255, verbose_name='Paid By')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income',
                'db_table': 'finance_income',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='finance_inc_created_f04fc1_idx')],
            },
        ),
    ]
