# Generated by Django 5.2.12 on 2026-07-26 12:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuesPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(db_index=True, help_text='The calendar year this dues payment covers.', verbose_name='Dues Year')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative amount paid for this year. May be partial.', max_digits=10, verbose_name='Amount Paid')),
                ('notes', models.TextField(blank=True, help_text="e.g., 'Paid in cash at meeting', 'Bank transfer ref: XYZ'", verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Dues Payment',
                'verbose_name_plural': 'Dues Payments',
                'db_table': 'finance_dues_payment',
                'ordering': ['-year', 'member__full_name'],
            },
        ),
        migrations.CreateModel(
            name='DuesPaymentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total Amount Paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('receipt_reference', models.CharField(blank=True, help_text='Bank transfer reference, receipt number, or any proof of payment ID.', max_length=255, verbose_name='Receipt / Reference Number')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Dues Payment Transaction',
                'verbose_name_plural': 'Dues Payment Transactions',
                'db_table': 'finance_association_dues',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('DUES', 'Yearly Dues'), ('DONATION', 'Donation / Contribution'), ('EVENT', 'Event Fee'), ('OTHER', 'Other')], db_index=True, default='DONATION', max_length=20, verbose_name='Income Type'),
        ),
        migrations.AddField(
            model_name='income',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Select if the contributor is a registered member', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='paid_by',
            field=models.CharField(blank=True, help_text='Name of payer (used if no member is selected)', max_length=255, verbose_name='Paid By'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_type'], name='finance_inc_income__906cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['member'], name='finance_inc_member__8e4e01_idx'),
        ),
        migrations.AddField(
            model_name='duespayment',
            name='income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dues_payment', to='finance.income', verbose_name='Linked Income Record'),
        ),
        migrations.AddField(
            model_name='duespayment',
            name='member',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='dues_payments', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='duespayment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By'),
        ),
        migrations.AddField(
            model_name='duespaymenttransaction',
            name='member',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='dues_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='duespaymenttransaction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dues_transactions_recorded', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By'),
        ),
        migrations.AddField(
            model_name='duespayment',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='dues_allocations', to='finance.duespaymenttransaction', verbose_name='Source Transactions'),
        ),
        migrations.AddConstraint(
            model_name='duespayment',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 2020)), name='year_gte_2020'),
        ),
        migrations.AddConstraint(
            model_name='duespayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='amount_paid_gte_zero'),
        ),
        migrations.AlterUniqueTogether(
            name='duespayment',
            unique_together={('member', 'year')},
        ),
    ]
