# Generated by Django 5.2.12 on 2026-07-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_duespayment_duespaymenttransaction_and_more'),
        ('operations', '0002_casefile_reported_to_casefile_resolved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Select the resolved case this fine was collected from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='operations.casefile', verbose_name='Related Case'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(choices=[('DUES', 'Yearly Dues'), ('DONATION', 'Donation / Contribution'), ('EVENT', 'Event Fee'), ('CASE_FINE', 'Case Fine / Resolution'), ('OTHER', 'Other')], db_index=True, default='DONATION', max_length=20, verbose_name='Income Type'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['case'], name='finance_inc_case_id_ac1dfa_idx'),
        ),
    ]
