# Generated by Django 5.2.11 on 2026-02-09 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_contribution_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='sender_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='sender_name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='DetailedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.finance')),
            ],
        ),
    ]
