# Generated by Django 5.2.11 on 2026-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_contribution_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='sender_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='income',
            name='sender_name',
            field=models.CharField(max_length=200),
        ),
    ]
