# Generated by Django 5.2.11 on 2026-02-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_income_sender_id_alter_income_sender_name'),
        ('finance', '0007_alter_income_sender_id_alter_income_sender_name_and_more'),
    ]

    operations = [
    ]
