# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(choices=[('President', 'President'), ('Deputy President', 'Deputy President'), ('Secretary', 'Secretary'), ('Assistant Secretary', 'Assistant Secretary'), ('Treasurer', 'Treasurer'), ('Financial Secretary', 'Financial Secretary'), ('Assistant Financial Secretary', 'Assistant Financial Secretary'), ('PRO', 'PRO'), ('Assistant PRO', 'Assistant PRO'), ('DOS', 'DOS'), ('Assistant DOS', 'Assistant DOS'), ('Auditor 1', 'Auditor 1'), ('Auditor 2', 'Auditor 2'), ('Provost 1', 'Provost 1'), ('Provost 2', 'Provost 2'), ('Provost 3', 'Provost 3')], max_length=50, verbose_name='Post')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=True, verbose_name='Is Current')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executive_roles', to='members.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Executive',
                'verbose_name_plural': 'Executives',
                'db_table': 'executives_executive',
                'ordering': ['-is_current', '-start_date'],
                'indexes': [models.Index(fields=['is_current'], name='executives__is_curr_128295_idx'), models.Index(fields=['post'], name='executives__post_3c1da0_idx'), models.Index(fields=['member'], name='executives__member__177954_idx')],
                'unique_together': {('member', 'post', 'is_current')},
            },
        ),
    ]
