# Generated by Django 5.2.12 on 2026-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executives', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='post',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Secretary', 'Secretary'), ('Assistant Secretary', 'Assistant Secretary'), ('Treasurer', 'Treasurer'), ('Financial Secretary', 'Financial Secretary'), ('Assistant Financial Secretary', 'Assistant Financial Secretary'), ('PRO', 'PRO'), ('Assistant PRO', 'Assistant PRO'), ('DOS', 'DOS'), ('Assistant DOS', 'Assistant DOS'), ('Auditor 1', 'Auditor 1'), ('Auditor 2', 'Auditor 2'), ('Provost 1', 'Provost 1'), ('Provost 2', 'Provost 2'), ('Provost 3', 'Provost 3')], max_length=50, verbose_name='Post'),
        ),
    ]
