# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PIN_RESET', 'PIN Reset'), ('ELECTION_ACTION', 'Election Action'), ('FINANCE_ACTION', 'Finance Action'), ('PROJECT_ACTION', 'Project Action'), ('CASE_ACTION', 'Case Action'), ('PERMISSION_CHANGE', 'Permission Change'), ('VIEW', 'View')], max_length=30, verbose_name='Action')),
                ('object_type', models.CharField(max_length=100, verbose_name='Object Type')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'auditlogs_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='auditlogs_a_user_id_4ecef3_idx'), models.Index(fields=['action'], name='auditlogs_a_action_b1f2ec_idx'), models.Index(fields=['object_type'], name='auditlogs_a_object__4b8cef_idx'), models.Index(fields=['created_at'], name='auditlogs_a_created_513404_idx'), models.Index(fields=['ip_address'], name='auditlogs_a_ip_addr_d9c5d2_idx')],
            },
        ),
    ]
