# Generated by Django 5.2 on 2026-07-28 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('executives', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'elections_election',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['status'], name='elections_e_status_idx'),
        ),
        migrations.AddIndex(
            model_name='election',
            index=models.Index(fields=['start_date'], name='elections_e_start_dt_idx'),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.CharField(max_length=50, verbose_name='Post')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='elections/candidates/%Y/%m/', verbose_name='Campaign Photo')),
                ('manifesto', models.TextField(blank=True, verbose_name='Manifesto')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Votes')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election', verbose_name='Election')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidacies', to='members.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'elections_candidate',
                'ordering': ['-votes', 'post'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'member', 'post')},
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.CharField(max_length=50, verbose_name='Post')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='elections.candidate', verbose_name='Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='elections.election', verbose_name='Election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_votes', to=settings.AUTH_USER_MODEL, verbose_name='Voter')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': 'elections_vote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election', 'post')},
        ),
        migrations.CreateModel(
            name='HandoverLedger',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenure_start', models.DateField(blank=True, help_text='Start date of this executive\'s tenure (for auto-calculating aggregates).', null=True, verbose_name='Tenure Start Date')),
                ('tenure_end', models.DateField(blank=True, help_text='End/handover date for this executive\'s tenure.', null=True, verbose_name='Tenure End Date')),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Bank Balance')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Cash Balance')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, help_text='All non-dues income recorded during the tenure period.', max_digits=15, verbose_name='Total Income Realized')),
                ('total_dues', models.DecimalField(decimal_places=2, default=0.0, help_text='Dues payments recorded during the tenure period.', max_digits=15, verbose_name='Total Dues Collected')),
                ('total_donations', models.DecimalField(decimal_places=2, default=0.0, help_text='Confirmed project donations received during the tenure period.', max_digits=15, verbose_name='Total Project Donations')),
                ('taskforce_revenue', models.DecimalField(decimal_places=2, default=0.0, help_text='Fines/revenue from resolved case files during the tenure period.', max_digits=15, verbose_name='Taskforce Revenue')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Expenses recorded during the tenure period.', max_digits=15, verbose_name='Total Expenses')),
                ('taskforce_total', models.PositiveIntegerField(default=0, verbose_name='Taskforce Total')),
                ('taskforce_active', models.PositiveIntegerField(default=0, verbose_name='Taskforce Active')),
                ('taskforce_inactive', models.PositiveIntegerField(default=0, verbose_name='Taskforce Inactive')),
                ('motorcycle_total', models.PositiveIntegerField(default=0, verbose_name='Motorcycles Total')),
                ('motorcycle_excellent', models.PositiveIntegerField(default=0, verbose_name='Motorcycles Excellent')),
                ('motorcycle_needs_service', models.PositiveIntegerField(default=0, verbose_name='Motorcycles Needs Service')),
                ('motorcycle_grounded', models.PositiveIntegerField(default=0, verbose_name='Motorcycles Grounded')),
                ('cases_total', models.PositiveIntegerField(default=0, verbose_name='Cases Total')),
                ('cases_open', models.PositiveIntegerField(default=0, verbose_name='Cases Open (Unattended)')),
                ('cases_in_progress', models.PositiveIntegerField(default=0, verbose_name='Cases In Progress (Ongoing)')),
                ('cases_resolved', models.PositiveIntegerField(default=0, verbose_name='Cases Resolved')),
                ('projects_completed', models.PositiveIntegerField(default=0, verbose_name='Projects Completed')),
                ('projects_at_hand', models.PositiveIntegerField(default=0, verbose_name='Projects At Hand (Ongoing)')),
                ('projects_future', models.PositiveIntegerField(default=0, verbose_name='Projects Future/Planned')),
                ('assets_description', models.TextField(blank=True, verbose_name='Assets Description')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('election', models.ForeignKey(blank=True, help_text='The election that resulted in this executive transition.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='elections.election', verbose_name='Related Election')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='executives.executive', verbose_name='Outgoing Executive')),
            ],
            options={
                'verbose_name': 'Handover Ledger',
                'verbose_name_plural': 'Handover Ledgers',
                'db_table': 'elections_handoverledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
