# Generated by Django 5.2.12 on 2026-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='election',
            new_name='elections_e_status_e3ccd0_idx',
            old_name='elections_e_status_idx',
        ),
        migrations.RenameIndex(
            model_name='election',
            new_name='elections_e_start_d_84de8e_idx',
            old_name='elections_e_start_dt_idx',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='handoverledger',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
