# Generated by Django 5.2.12 on 2026-07-28 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_joined',
            field=models.PositiveIntegerField(default=2020, help_text='The year this member joined the association.', validators=[django.core.validators.MinValueValidator(2020, message='Join year cannot be before platform creation (2020).')], verbose_name='Year Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXECUTIVE', 'Executive'), ('FLOOR_MEMBER', 'Floor Member')], default='ADMIN', max_length=20, verbose_name='Role'),
        ),
    ]
