# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True, verbose_name='Case Number')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Fine Amount')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20, verbose_name='Status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Resolution Notes')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='Resolved Date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='members.member', verbose_name='Respondent')),
            ],
            options={
                'verbose_name': 'Case File',
                'verbose_name_plural': 'Case Files',
                'db_table': 'operations_casefile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='operations__status_2dbaba_idx'), models.Index(fields=['case_number'], name='operations__case_nu_f264b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Asset Tag')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brand')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('NEEDS_SERVICE', 'Needs Service'), ('GROUNDED', 'Grounded')], default='EXCELLENT', max_length=20, verbose_name='Condition')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_motorcycles', to='members.member', verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Motorcycle',
                'verbose_name_plural': 'Motorcycles',
                'db_table': 'operations_motorcycle',
                'ordering': ['asset_tag'],
                'indexes': [models.Index(fields=['condition'], name='operations__conditi_a4dc36_idx'), models.Index(fields=['assigned_to'], name='operations__assigne_61741d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskForceMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(verbose_name='Assigned Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_force_assignments', to='members.member', verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Task Force Member',
                'verbose_name_plural': 'Task Force Members',
                'db_table': 'operations_taskforcemember',
                'ordering': ['-assigned_date'],
                'indexes': [models.Index(fields=['is_active'], name='operations__is_acti_1152d5_idx'), models.Index(fields=['assigned_date'], name='operations__assigne_03f90c_idx')],
            },
        ),
    ]
