# Generated by Django 5.2.12 on 2026-07-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='reported_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to='operations.taskforcemember', verbose_name='Reported To'),
        ),
        migrations.AddField(
            model_name='casefile',
            name='resolved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to='operations.taskforcemember', verbose_name='Resolved By'),
        ),
    ]
