# Generated by Django 5.2.12 on 2026-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_casefile_reported_to_casefile_resolved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Case Number'),
        ),
    ]
