# Generated by Django 5.2.15 on 2026-06-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yearly_dues', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10, verbose_name='Yearly Dues')),
                ('minimum_age', models.PositiveIntegerField(default=18, verbose_name='Minimum Age')),
                ('past_member_age', models.PositiveIntegerField(default=56, verbose_name='Past Member Age')),
                ('primary_color', models.CharField(default='#1a237e', max_length=7, verbose_name='Primary Color')),
                ('accent_color', models.CharField(default='#ff6f00', max_length=7, verbose_name='Accent Color')),
                ('theme_mode', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('AUTO', 'Auto')], default='LIGHT', max_length=10, verbose_name='Theme Mode')),
                ('association_name', models.CharField(default='Okpo Youths Association', max_length=255, verbose_name='Association Name')),
                ('motto', models.CharField(default='PEACE & PROGRESS', max_length=100, verbose_name='Motto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'settingsapp_systemsettings',
            },
        ),
    ]
