# Generated by Django 5.2.12 on 2026-07-28 18:09

import settingsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Recommended: 32x32 or 64x64 ICO/PNG, max 1MB. Shown in browser tab.', null=True, upload_to=settingsapp.models.favicon_upload_path, verbose_name='Browser Favicon'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended: PNG with transparent background, max 2MB. Used in header, login page, and emails.', null=True, upload_to=settingsapp.models.logo_upload_path, verbose_name='Organization Logo'),
        ),
    ]
