# Generated by Django 5.2.12 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settingsapp', '0003_donationgroup_donationgroupmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='donationgroup',
            new_name='settingsapp_is_acti_5c4105_idx',
            old_name='settingsapp_dg_active_idx',
        ),
        migrations.RenameIndex(
            model_name='donationgroup',
            new_name='settingsapp_name_d693a9_idx',
            old_name='settingsapp_dg_name_idx',
        ),
        migrations.RenameIndex(
            model_name='donationgroupmembership',
            new_name='settingsapp_group_i_4ad174_idx',
            old_name='settingsapp_dgm_grp_mem_idx',
        ),
        migrations.RenameIndex(
            model_name='donationgroupmembership',
            new_name='settingsapp_member__fc218d_idx',
            old_name='settingsapp_dgm_member_idx',
        ),
    ]
