# Generated by Django 5.2.15 on 2026-06-10 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Clan Name')),
            ],
            options={
                'verbose_name': 'Clan',
                'verbose_name_plural': 'Clans',
                'db_table': 'members_clan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20, unique=True, verbose_name='Serial Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='Age')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/%Y/%m/', verbose_name='Photo')),
                ('state_or_abroad', models.CharField(blank=True, max_length=100, verbose_name='State or Abroad')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_MEMBER', 'Past Member'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('offense_committed', models.TextField(blank=True, verbose_name='Offense Committed')),
                ('removal_reason', models.TextField(blank=True, verbose_name='Removal Reason')),
                ('umu_nna_clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.clan', verbose_name='Umu Nna Clan')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'db_table': 'members_member',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='members_mem_status_734de0_idx'), models.Index(fields=['umu_nna_clan'], name='members_mem_umu_nna_689a56_idx'), models.Index(fields=['serial_number'], name='members_mem_serial__f0ba0f_idx'), models.Index(fields=['full_name'], name='members_mem_full_na_3f8d20_idx')],
            },
        ),
    ]
