# Generated by Django 5.2.15 on 2026-06-10 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_seed_clans'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_abroad',
            field=models.BooleanField(default=False, verbose_name='Living Abroad?'),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18.'), django.core.validators.MaxValueValidator(55, message='Age must not exceed 55.')], verbose_name='Age'),
        ),
    ]
