# Generated by Django 5.2.12 on 2026-07-24 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_is_abroad_alter_member_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year_joined',
            field=models.PositiveIntegerField(default=2020, help_text='The year this member joined the association. Dues will only be tracked from this year onward.', validators=[django.core.validators.MinValueValidator(2020, message='Join year cannot be before platform creation (2020).')], verbose_name='Year Joined'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['year_joined'], name='members_mem_year_jo_a9d90b_idx'),
        ),
    ]
